modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
issueTrackerURL = "https://github.com/FabiPunktExe/OresOresOres/issues"

[[mods]]
modId = "oresoresores"
version = "${version}"
displayName = "Ores Ores Ores"
displayURL="https://github.com/FabiPunktExe/OresOresOres"
logoFile = "icon.png"
authors = "Fabi.exe"
description = '''
Adds many (maybe not useful) ores.
'''

[[dependencies.oresoresores]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.oresoresores]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"

[[dependencies.oresoresores]]
modId = "architectury"
mandatory = true
versionRange = "[4.12.94,)"
ordering = "AFTER"
side = "BOTH"
